apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  project: default
  source:
    path: .
    repoURL: https://github.com/sheveg/postgres-helm.git
    targetRevision: main
    helm:
      releaseName: postgres-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true