apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgres
  project: default
  sources:
    - chart: postgres-operator
      path: .
      repoURL: https://opensource.zalando.com/postgres-operator/charts/
      targetRevision: 1.10.0
      helm:
        releaseName: postgres-operator
        valuesObject:
          min_instances: 1
          max_instances: 1
    - chart: postgres-operator-ui
      path: .
      repoURL: https://opensource.zalando.com/postgres-operator/charts/
      targetRevision: 1.10.0
      helm:
        releaseName: postgres-operator-ui
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true