apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-helm
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  project: default
  source:
    path: .
    repoURL: https://github.com/sheveg/strimzi-operator.git
    targetRevision: main
    helm:
      releaseName: strimzi
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true