apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  project: default
  source:
    chart: strimzi-kafka-operator
    path: .
    repoURL: https://strimzi.io/charts/
    targetRevision: 0.36.1
    helm:
      releaseName: strimzi
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true