apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-registry-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  project: default
  source:
    chart: strimzi-registry-operator
    path: .
    repoURL: https://lsst-sqre.github.io/charts/
    targetRevision: 2.1.0
    helm:
      valuesObject:
        clusterName: kafka-cluster
        clusterNamespace: kafka
        operatorNamespace: kafka
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true